MarketWebApp/Controllers/DashBordController.cs
using MarketWebApp.Repository.ProductRepository;
using MarketWebApp.Repository.SupplierRepository;
using MarketWebApp.Reprository.CategoryReprositry;
using MarketWebApp.Reprository.OrderReprository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MarketWebApp.Controllers
{
   [Authorize(Roles = "Admin")]
    public class DashBordController : Controller
    {
        private readonly IProductRepository productReprository;
        private readonly ICategoryRepository categoryReprository;
        private readonly ISupplierRepository supplierRepository;
        private readonly IOrderAdminRepository orderRepository;


        public DashBordController(IProductRepository productReprository,
            ICategoryRepository categoryReprository, ISupplierRepository supplierRepository
            , IOrderAdminRepository orderReprository)
        {
            this.productReprository = productReprository;
            this.categoryReprository = categoryReprository;
            this.supplierRepository = supplierRepository;
            this.orderRepository = orderReprository;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            ViewBag.productCount = productReprository.GetAll().Count();
            ViewBag.CategoryCount = categoryReprository.GetAll().Count();
            ViewBag.SupplierCount = supplierRepository.GetAll().Count();
            ViewBag.orderCount = orderRepository.GetAll().Count();
            return View();
        }
    }
}

MarketWebApp/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MarketWebApp.Data;
using MarketWebApp.Models.Entity;
using MarketWebApp.Repository.LocationRepository;
using MarketWebApp.Repository.SupplierRepository;
using MarketWebApp.ViewModel;
using MarketWebApp.ViewModel.Location;
using NuGet.Protocol.Core.Types;
using Microsoft.AspNetCore.Authorization;

namespace MarketWebApp.Controllers
{
    public class LocationsController : Controller
    {
        private readonly ILocationRepository locationRepository;

        public LocationsController(ILocationRepository locationRepository)
        {
            this.locationRepository = locationRepository;
        }

        // GET: Locations
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            ViewBag.PageCount = (int)Math.Ceiling((decimal)locationRepository.GetAll().Count() / 5m);

            return View(locationRepository.GetAll());
        }

        // GET: Locations/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult CheckLocationExist(string Name)
        {
            if (locationRepository.CheckLocationExist(Name))
                return Json(true);
            else
                return Json(false);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult CheckLocationExistEdit(string Name, int Id)
        {
            if (locationRepository.CheckLocationExistEdit(Name, Id))
                return Json(true);
            else
                return Json(false);
        }

        // POST: Locations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(AddLocationViewModel locationViewModel)
        {
            if (ModelState.IsValid)
            {
                string locationNameToLower = locationViewModel.Name.ToLower(); // Convert input name to lowercase

                if (locationRepository.GetAll().Any(c => c.Name.ToLower() == locationNameToLower))
                {
                    ModelState.AddModelError("", "Location with the same name already exists.");
                    return View(locationViewModel);
                }

                try
                {
                    locationRepository.Insert(locationViewModel);
                    locationRepository.Save();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(locationViewModel);
                }
            }
            else
            {
                return View(locationViewModel);
            }
        }


        // GET: Locations/Edit/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int Id)
        {
            var location = locationRepository.GetLocation(Id);
            EditLocationViewModel locationViewModel = new EditLocationViewModel();
            locationViewModel.ID = location.ID;
            locationViewModel.Name = location.Name;
            return View(locationViewModel);
        }

        // POST: Locations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(EditLocationViewModel locationViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string locationNameToLower = locationViewModel.Name.ToLower(); // Convert input name to lowercase

                    if (!locationRepository.IsLocationNameUnique(locationViewModel.ID, locationNameToLower))
                    {
                        ModelState.AddModelError("Name", "Location name already exists.");
                        return View(locationViewModel);
                    }

                    locationRepository.Update(locationViewModel);
                    locationRepository.Save();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(locationViewModel);
                }
            }
            else
            {
                return View(locationViewModel);
            }
        }

        public IActionResult GetLocation(int pageNumber, int pageSize = 5, string searchQuery = "")
        {
            // Check if there's a search query
            if (!string.IsNullOrEmpty(searchQuery))
            {
                var locations = locationRepository.SearchByName(searchQuery)
                    .OrderBy(p => p.ID)
                    .Skip((pageNumber - 1) * pageSize)
                    .Take(pageSize)
                    .ToList();

                return PartialView("_LocationTable", locations);
            }
            else
            {
                var locations = locationRepository.GetAll()
                    .OrderBy(p => p.ID)
                    .Skip((pageNumber - 1) * pageSize)
                    .Take(pageSize)
                    .ToList();

                return PartialView("_LocationTable", locations);
            }
        }

        // GET: Locations/Delete/5
        [HttpGet]
        public IActionResult Delete(int Id)
        {
            return View(locationRepository.GetLocation(Id));
        }

        // POST: Locations/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmDelete(int Id)
        {
            if (ModelState.IsValid)
            {
                locationRepository.Delete(Id);
                locationRepository.Save();
                return RedirectToAction("Index");
            }
            return View("Delete");
        }
    }
}

MarketWebApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MarketWebApp.Data;
using MarketWebApp.Models.Entity;
using Microsoft.AspNetCore.Authorization;
using MarketWebApp.Reprository.CategoryReprositry;
using MarketWebApp.Repository.ProductRepository;
using NuGet.Protocol.Core.Types;
using MarketWebApp.Repository.SupplierRepository;
using MarketWebApp.ViewModel.Product;
using MarketWebApp.ViewModel;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace MarketWebApp.Controllers
{
    [Authorize(Roles = "Admin")]

    public class ProductsController : Controller
    {
        private readonly IProductRepository repository;
        private readonly ICategoryRepository repositorycaty;
        private readonly ISupplierRepository repositorySupplier;
        private readonly ApplicationDbContext context;

        public ProductsController(IProductRepository repository, ICategoryRepository repositorycaty ,ISupplierRepository repositorySupplier ,ApplicationDbContext _context)
        {
            this.repository = repository;
            this.repositorycaty = repositorycaty;
            this.repositorySupplier = repositorySupplier;
            this.context = _context;

        }

        // GET: Products

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            ViewBag.PageCount = (int)Math.Ceiling((decimal)repository.GetAll().Count() / 5m);
            return View(this.repository.GetAll());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult GetProducts(int pageNumber, int pageSize = 5, string searchQuery = "")
        {
            // Check if there's a search query
            if (!string.IsNullOrEmpty(searchQuery))
            {
                var products = repository.SearchByName(searchQuery)
                    .OrderBy(p => p.ID)
                    .Skip((pageNumber - 1) * pageSize)
                    .Take(pageSize)
                    .ToList();

                return PartialView("_ProductTable", products);
            }
            else
            {
                var products = repository.GetAll()
                    .OrderBy(p => p.ID)
                    .Skip((pageNumber - 1) * pageSize)
                    .Take(pageSize)
                    .ToList();

                return PartialView("_ProductTable", products);
            }
        }

        // GET: Products/Create

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(repositorycaty.GetAll(), "ID", "Name");
            ViewData["SupplierId"] = new SelectList(repositorySupplier.GetAll(), "ID", "Name");
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Admin")]
        public IActionResult Create(AddProductViewModel addProductViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string productNameToLower = addProductViewModel.Name.ToLower(); // Convert input name to lowercase

                    // Check if a product with the same name already exists for the same supplier and category
                    bool productNameExists = repository.GetAll()
                        .Any(p => p.Name.ToLower() == productNameToLower &&
                                   p.SupplierId == addProductViewModel.SupplierId &&
                                   p.CategoryId == addProductViewModel.CategoryID);

                    if (productNameExists)
                    {
                        ModelState.AddModelError("Name", "Product name already exists for the same supplier and category.");
                        PopulateDropdowns();
                        return View(addProductViewModel);
                    }

                    // Insert the new product into the repository
                    repository.Insert(addProductViewModel);
                    repository.Save();

                    // Redirect to the index action after successful creation
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    PopulateDropdowns();
                    return View(addProductViewModel);
                }
            }
            else
            {
                // If the model state is not valid, return the view with the model to display validation errors
                return View(addProductViewModel);
            }
        }



        [Authorize(Roles = "Admin")]
        private void PopulateDropdowns()
        {
            // Populate dropdown lists for categories and suppliers
            ViewData["CategoryID"] = new SelectList(repositorycaty.GetAll(), "ID", "Name");
            ViewData["SupplierId"] = new SelectList(repositorySupplier.GetAll(), "ID", "Name");
        }


        // GET: Products/Edit/5
        [HttpGet]

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int Id)
        {
            var product = repository.GetProduct(Id);
            EditProductViewModel editProductViewModel = new EditProductViewModel();

            editProductViewModel.ID = product.ID;
            editProductViewModel.Name = product.Name;
            editProductViewModel.Image = product.Img;
            editProductViewModel.Price = product.Price;
            editProductViewModel.Detail = product.Detail;
            editProductViewModel.Unit = product.Unit;
            editProductViewModel.Discount = product.Discount;
            editProductViewModel.Stock = product.Stock;
            editProductViewModel.CategoryID = product.CategoryId;
            editProductViewModel.SupplierId = product.SupplierId;
            ViewData["CategoryID"] = new SelectList(repositorycaty.GetAll(), "ID", "Name", repositorycaty.GetCategory(editProductViewModel.CategoryID));
            ViewData["SupplierId"] = new SelectList(repositorySupplier.GetAll(), "ID", "Name", repositorySupplier.GetSupplier(editProductViewModel.SupplierId));

            return View(editProductViewModel);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(EditProductViewModel editProductViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string productNameToLower = editProductViewModel.Name.ToLower(); // Convert input name to lowercase

                    // Check if a product with the same name already exists for the same supplier and category
                    if (!repository.IsProductUnique(editProductViewModel.ID, productNameToLower, editProductViewModel.SupplierId, editProductViewModel.CategoryID))
                    {
                        ModelState.AddModelError("Name", "Product name already exists for the same supplier and category.");
                        PopulateDropdowns(editProductViewModel); // Populate dropdowns again for the view
                        return View(editProductViewModel);
                    }

                    repository.Update(editProductViewModel);
                    repository.Save();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    PopulateDropdowns(editProductViewModel); // Populate dropdowns again for the view
                    return View(editProductViewModel);
                }
            }
            else
            {
                PopulateDropdowns(editProductViewModel); // Populate dropdowns again for the view
                return View(editProductViewModel);
            }
        }

        [Authorize(Roles = "Admin")]
        private void PopulateDropdowns(EditProductViewModel editProductViewModel)
        {
            ViewData["CategoryID"] = new SelectList(repositorycaty.GetAll(), "ID", "Name", editProductViewModel.CategoryID);
            ViewData["SupplierId"] = new SelectList(repositorySupplier.GetAll(), "ID", "Name", editProductViewModel.SupplierId);
        }


        [Authorize(Roles = "Admin")]
        public IActionResult CheckProductExist(string Name)
        {
            if (repository.CheckProductExist(Name))
                return Json(true);
            else
                return Json(false);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult CheckProductExistEdit(string Name, int Id)
        {
            if (repository.CheckProductExistEdit(Name, Id))
                return Json(true);
            else
                return Json(false);
        }

        // GET: Products/Delete/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int Id)
        {
            return View(repository.GetProduct(Id));
        }

        // POST: Products/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Admin")]
        public IActionResult ConfirmDelete(int Id)
        {
            var orderPending = context.Orders.Any(o => o.State == "Pending" && o.OrderProducts.Any(op => op.ProductId == Id));

            if (!orderPending)
            {
                if (ModelState.IsValid)
                {
                    repository.Delete(Id);
                    repository.Save();
                    return RedirectToAction("Index");
                }
                return View("Delete", repository.GetProduct(Id));
            }
            else
            {

MarketWebApp/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewBag.Title</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">



    <link href="~/css/style.css" rel="stylesheet" />
    <style>
        table {
            text-align: center;
        }

        h1 {
            font-size: 50px;
        }

        .p-3 {
            padding: 2rem !important;
        }
        .p-5
        {
            padding-bottom: 0rem !important;
            padding-top: 3rem !important;
            padding-right: 3rem !important;
            padding-left: 3rem !important;
        }

        h1.fw-bold.mb-0.fs-3 {
            font-weight: 500;
        }
        h1.fw-bold.mb-0.fs-2 {
            font-weight: 600;
            font-size: 43px;
        }

        .card-cant {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            
            position: relative;
            display: -ms-flexbox;
            -ms-flex-direction: column;
            min-width: 0;
            word-wrap: break-word;
            background-color: #fff;
            background-clip: border-box;
            border: 1px solid rgba(0, 0, 0, .125);
            border-radius: 0.25rem;
        }

        .card-cant img {
            max-width: 60%;
            display: block; /* Ensures the image is a block element for centering */
            margin: 0 auto; /* Centers the image horizontally within its parent */
            padding: 1rem;
        }

        .custom-btn-style {
            background-color: black;
            color: white;
        }

        .btn:hover {
            color: #212529;
            text-decoration: none;
        }

        .btn-outline-light:hover {
            color: #212529;
            background-color: #7c7f83;
        }
        /* Define the color for the active page */
        .page-item.active .page-link {
            background-color: black;
            border-color: gray;
        }

        /* Define the text color for the active page */
        .page-item.active .page-link {
            color: #ffffff; /* White text on green background */
        }

        #searching {
            display: flex;
            flex-wrap: wrap;
            margin-right: -15px;
            margin-left: -15px;
            justify-content: space-around;
        }
    </style>
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Humberger Begin -->
   <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/img/se7teen-logo.png" /> </a>
        </div>
        <div class="humberger__menu__widget">
            <div class="header__top__right__auth">
                <a asp-area="" asp-controller="Account" asp-action="Logout"><i class="fa fa-user"></i>Welcome @User.Identity?.Name!</a>
                @* <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a> *@

            </div>
        </div>
        <nav class="humberger__menu__nav mobile-menu" >
                <ul>
                    <li ><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="active">
                    <a class="nav-link " asp-area="" asp-controller="DashBord" asp-action="Index">DashBord</a>
                </li>
                    <li>
                        <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">Department</a>
                    </li>
                    <li><a class="nav-link" asp-area="" asp-controller="Suppliers" asp-action="Index">Supplier</a></li>
                    <li>
                        <a class="nav-link" asp-area="" asp-controller="Products" asp-action="Index">Product</a>
                    </li>
                    @* <li>
                        <a class="nav-link" asp-area="" asp-action="UserHistory" asp-controller="ConfirmOrder">History</a>
                    </li> *@
                    <li>
                    <a class="nav-link" asp-area="" asp-action="Index" asp-controller="ConfirmOrder">Order</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-area="" asp-controller="Locations" asp-action="Index">Location</a>
                    </li>
                </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="header__top__right__social"></div>
        <div class="humberger__menu__contact">
            <ul>
                <li><i class="fa fa-envelope"></i>Welcome @User.Identity?.Name!</li>
                <li>Ramadan Kareem 🌙</li>
            </ul>
        </div>
    </div>


    <!-- _________________________- Screen - ___________________________-- -->
    <!-- Humberger End -->
    <!-- Header Section Begin -->
    <header class="header">
         <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__left">
                            <ul>
                                <li><i class="fa fa-envelope"></i> Welcome @User.Identity?.Name!</li>
                                <li>Ramadan Kareem 🌙</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__auth">
                                @if (User.Identity?.IsAuthenticated == false)
                                {
                                    <div class="header__top__right__auth">
                                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>

                                    </div>
                                }
                                else
                                {
                                    <form class="header__top__right__auth" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="/" method="post">
                                        <a href="#" class="nav-link text-dark" onclick="this.closest('form').submit(); return false;">Logout</a>
                                    </form>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

 
        <div class="container">
            <div class="row">
                 <div class="col-lg-2">
                @*    <div class="header__logo"> *@
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/se7teen-logo.png" /></a>
                   @*  </div>*@
                </div> 
                <div class="col-lg-9">
                    <nav class="header__menu">
                        <ul>
                            <li><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="active">
                                <a class="nav-link " asp-area="" asp-controller="DashBord" asp-action="Index">DashBord</a>
                            </li>
                            <li>
                                <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">Department</a>
                            </li>
                            <li><a class="nav-link" asp-area="" asp-controller="Suppliers" asp-action="Index">Supplier</a></li>
                            <li>
                                <a class="nav-link" asp-area="" asp-controller="Products" asp-action="Index">Product</a>
                            </li>
                            <li>
                                <a class="nav-link" asp-area="" asp-action="Index" asp-controller="ConfirmOrder">Order</a>
                            </li>
                           @*  <li>
                                <a class="nav-link" asp-area="" asp-action="UserHistory" asp-controller="ConfirmOrder">History</a>
                            </li> *@
                            <li>
                                <a class="nav-link" asp-area="" asp-controller="Locations" asp-action="Index">Location</a>
                            </li>
                        </ul>
                    </nav>
                </div>
               @*  <div class="col-lg-3">
                </div> *@
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>


    <br>
    <div>
        @RenderBody()
    </div>
    <!-- Js Plugins -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/jquery.slicknav.js"></script>
    <script src="~/js/mixitup.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/main.js"></script>



    @RenderSection("scripts", required: false)

</body>

</html>