MarketWebApp/Models/Entity/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MarketWebApp.Models.Entity
{
    public class Product
    {
        [Key]
        public int ID { get; set; }

        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Price is required")]
        public float Price { get; set; }

        public float Discount { get; set; }
        [Display(Name = "Image")]
        public string Img { get; set; }
        public string Detail { get; set; }
        public string Unit { get; set; }

        [Required(ErrorMessage = "Stock is required")]
        public int Stock { get; set; }

        [ForeignKey("Supplier")]
        public int SupplierId { get; set; }
        public virtual Supplier Supplier { get; set; }

        [ForeignKey("Category")]
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }

        // Navigation property to the join entity
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ICollection<ProductCart> ProductCarts { get; set; }
       


    }
}

MarketWebApp/Controllers/ShopController.cs
using MarketWebApp.Data;
using MarketWebApp.Models.Entity;
using Microsoft.AspNetCore.Mvc;

namespace MarketWebApp.Controllers
{
    public class ShopController : BaseController
    {
        ApplicationDbContext context;
        public ShopController(ApplicationDbContext _context) : base(_context)
        {
            context = _context;
        }
        public IActionResult Index(int page = 1)
        {
            int pageSize = 9; // Number of items per page

            var totalItems = context.Products.Where(Product => Product.Discount == 0 && Product.Stock > 0).Count();
            var totalPages = (int)Math.Ceiling((double)totalItems / pageSize);
            var products = context.Products
                                        .Where(Product => Product.Discount == 0 && Product.Stock > 0)
                                        .Skip((page - 1) * pageSize)
                                        .Take(pageSize)
                                        .ToList();
            var Model = new
            {
                Products = products,
                CurrentPage = page,
                Count = products.Count(),
                TotalPages = totalPages,
                Discount = context.Products.Where(Product => Product.Discount > 0 && Product.Stock > 0).ToList(),
            };
            return View(Model);
        }

        [HttpGet]
        public IActionResult Product(int id)
        {
            var products = context.Products.Where(P => P.CategoryId == id && P.Discount == 0 && P.Stock > 0);
            var Model = new
            {
                Products = products,
                Count = products.Count(),
                Discount = context.Products.Where(Product => Product.Discount > 0 && Product.Stock > 0).ToList(),
            };
            return View(Model);

        }
    }
}

MarketWebApp/Controllers/ShoppingCartController.cs
using MarketWebApp.Data;
using MarketWebApp.Models;
using MarketWebApp.Models.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MarketWebApp.Controllers
{
    public class ShoppingCartController : BaseController
    {

        private readonly ApplicationDbContext _context;

        public ShoppingCartController(ApplicationDbContext context) : base(context)
        {
            _context = context;
        }

        public IActionResult Delete(int? id)
        {
            var sh = _context.ProductCart.FirstOrDefault(s=>s.ID==id);
            if (sh == null)
            {
                return NotFound();
            }

            _context.ProductCart.Remove(sh);
            _context.SaveChanges();
            TempData["DeletedMessage"] = "Product deleted from ShoppingCart successfully.";
            return RedirectToAction("Index");
        }




        [HttpPost]
        [Authorize]
        public IActionResult AddToCart(int id)
        {
            string userId = HttpContext.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;


            if (userId == null)
            {
                TempData["UserNotFound"] = "Please log in to add items to your cart.";
                return RedirectToAction("Index", "Home");
            }

          
            var shoppingCart = _context.ShoppingCart.Include(sc => sc.ProductCarts)
                                        .FirstOrDefault(cart => cart.ApplicationUserID == userId);


            if (shoppingCart == null)
            {
                shoppingCart = new ShoppingCart
                {
                    ApplicationUserID = userId,
                    ProductCarts = new List<ProductCart>()
                };
                _context.ShoppingCart.Add(shoppingCart);
            }

            var existingProductCart = shoppingCart.ProductCarts.FirstOrDefault(pc => pc.ProductId == id);

            if (existingProductCart != null)
            {
                //existingProductCart.Quantity++;
                TempData["DuplicateMessage"] = "This product is already in your shopping cart.";
            }
            else
            {
                var newProductCart = new ProductCart
                {
                    ProductId = id,
                    Quantity = 1
                };
                shoppingCart.ProductCarts.Add(newProductCart);
            TempData["SuccessMessage"] = "Product added to ShoppingCart successfully.";
            }

            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        public IActionResult UpdateQuantity(int id, int quantity)
        {
            string userId = HttpContext.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;

            if (userId == null)
            {
                TempData["UserNotFound"] = "Please log in to add items to your cart.";
                return RedirectToAction("Index", "Home");
            }

            var shoppingCart = _context.ShoppingCart
                .Include(sc => sc.ProductCarts)
                .FirstOrDefault(cart => cart.ApplicationUserID == userId);

            if (shoppingCart == null)
            {
                shoppingCart = new ShoppingCart
                {
                    ApplicationUserID = userId,
                    ProductCarts = new List<ProductCart>()
                };
                _context.ShoppingCart.Add(shoppingCart);
            }

            var existingProductCart = shoppingCart.ProductCarts.FirstOrDefault(pc => pc.ProductId == id);

            if (existingProductCart != null)
            {
                existingProductCart.Quantity = quantity;
            }
            else
            {
                var newProductCart = new ProductCart
                {
                    ProductId = id,
                    Quantity = quantity
                };
                shoppingCart.ProductCarts.Add(newProductCart);
            }

            _context.SaveChanges();
            return RedirectToAction("Index", "shoppingcart");
        }
    


    public IActionResult Index()
        {
            string userId = HttpContext.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
            // Retrieve the shopping cart associated with the user
            var shoppingCart = _context.ShoppingCart
                                        .Include(cart => cart.ProductCarts)
                                            .ThenInclude(pc => pc.Product)
                                        .FirstOrDefault(cart => cart.ApplicationUserID == userId);

            if (shoppingCart == null)
            {
                // Handle the case where the user's shopping cart is empty
                TempData["EmptyShoppingCart"]= "Your shopping cart is empty.";
                return View(new List<ProductCart>());
            }

            // Pass the products in the shopping cart to the view
            return View(shoppingCart.ProductCarts);
        }


    }
}

MarketWebApp/Controllers/WishListController.cs
using MarketWebApp.Data;
using MarketWebApp.Models.Entity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NuGet.Protocol;

namespace MarketWebApp.Controllers
{
    public class WishListController : BaseController
    {

        IHttpContextAccessor _contx;
        ApplicationDbContext context;
        List<Product> products;

        public WishListController(ApplicationDbContext _context, IHttpContextAccessor contx):base(_context)
        {
            context = _context;
            _contx = contx;
            products = new List<Product>();


        }

        [HttpPost]
        public ActionResult AddProductToWish(int id)
        {
            var wish = context.Products.Find(id);
            
            var existingWishlistData = _contx.HttpContext.Session.GetString("ProductData");
            List<Product> products = new List<Product>();

            if (!string.IsNullOrEmpty(existingWishlistData))
            {
                products = JsonConvert.DeserializeObject<List<Product>>(existingWishlistData);

                if (products.Any(p => p.ID == wish.ID ))
                {
                    TempData["DuplicateMessage"] = "This product is already in your wishlist.";
                    return RedirectToAction("Index", "Home");
                }
            }

            products.Add(wish);

            var serializerSettings = new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            };

            string updatedProductString = JsonConvert.SerializeObject(products, serializerSettings);

            _contx.HttpContext.Session.SetString("ProductData", updatedProductString);
            TempData["SuccessMessage"] = "Product added to wishlist successfully.";
            return RedirectToAction("Index", "Home");

        }
        public IActionResult WishIndex()
        {

            string productString = _contx.HttpContext.Session.GetString("ProductData");
            if (!string.IsNullOrEmpty(productString))
            {

                products = JsonConvert.DeserializeObject<List<Product>>(productString);
            }

            return View(products);
        }


        public ActionResult RemoveProductFromWish(int id)
        {
            var existingWishlistData = _contx.HttpContext.Session.GetString("ProductData");
            List<Product> products = new List<Product>();

            if (!string.IsNullOrEmpty(existingWishlistData))
            {
                products = JsonConvert.DeserializeObject<List<Product>>(existingWishlistData);

                var productToRemove = products.FirstOrDefault(p => p.ID == id);
                if (productToRemove != null)
                {
                    products.Remove(productToRemove);

                    string updatedProductString = JsonConvert.SerializeObject(products);

                    _contx.HttpContext.Session.SetString("ProductData", updatedProductString);
                }
            }
            TempData["DeletedMessage"] = "Product deleted from wishlist successfully.";

            return RedirectToAction("WishIndex");
        }

    }
}

MarketWebApp/Views/Shop/Index.cshtml
 @model dynamic
@{
    ViewData["Title"] = "Shop";
}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg=@Url.Content("~/img/breadcrumb.jpg")>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Se7teenW3fia</h2>
                    <div class="breadcrumb__option">
                        <a href="./index.html">Home</a>
                        <span>Shop</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->
<!-- Product Section Begin -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-5">
                <div class="sidebar">
                    <div class="sidebar__item">
                        <h4>Department</h4>
                        <ul>
                            @foreach (var Catagory in ViewBag.Categories)
                            {
                                <li><a href="~/shop/product/@Catagory.ID">@Catagory.Name</a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-7">
                <div class="product__discount">
                    <div class="section-title product__discount__title">
                        <h2>Sale Off</h2>
                    </div>
                    <div class="row">
                        <div class="product__discount__slider owl-carousel">
                            @foreach (var DProduct in Model.Discount)
                            {
                                <div class="col-lg-4">
                                    <div class="product__discount__item">
                                        <div class="product__discount__item__pic set-bg" data-setbg=@Url.Content("~/img/product/" + DProduct.Img)>
                                            <div class="product__discount__percent">-@DProduct.Discount %</div>
                                            <ul class="product__item__pic__hover">
                                                <li>
                                                    <form onsubmit="return ADDWish(this);" asp-action="AddProductToWish" asp-controller="WishList" asp-route-id="@DProduct.ID">
                                                        <button type="submit" style="border:none; background-color:transparent">
                                                            <a><i class="fa fa-heart"></i></a>
                                                        </button>
                                                    </form>
                                                </li>
                                                <li>
                                                    <form onsubmit="return ADDCart(this);" method="post" asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@DProduct.ID">
                                                        <button type="submit" style="border:none; background-color:transparent">
                                                            <a><i class="fa fa-shopping-cart"></i></a>
                                                        </button>
                                                    </form>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="product__discount__item__text">
                                            <h5><a href="~/home/Details/@DProduct.ID">@DProduct.Name</a></h5>
                                            <div class="product__item__price">@(DProduct.Price - (DProduct.Price * DProduct.Discount / 100)) L.E <span>@DProduct.Price L.E</span></div>
                                        </div>
                                    </div>
                                </div>
                            };
                        </div>
                    </div>
                </div>
                <div class="filter__item">
                    <div class="row">
                        <div class="col-lg-4 col-md-5">
                        </div>
                        <div class="col-lg-4 col-md-3">
                            <div class="filter__found">
                                <h6><span>@Model.Count</span> Products found</h6>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    @foreach (var product in Model.Products)
                    {
                        <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="product__item">
                                <div class="product__item__pic set-bg" data-setbg=@Url.Content("~/img/product/" + product.Img)>
                                    <ul class="product__item__pic__hover">
                                        <li>
                                            <form onsubmit="return ADDWish(this);" asp-action="AddProductToWish" asp-controller="WishList" asp-route-id="@product.ID">
                                                <button type="submit" style="border:none; background-color:transparent">
                                                    <a><i class="fa fa-heart"></i></a>
                                                </button>
                                            </form>
                                        </li>
                                        <li>
                                            <form onsubmit="return ADDCart(this);" method="post" asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@product.ID">
                                                <button type="submit" style="border:none; background-color:transparent">
                                                    <a><i class="fa fa-shopping-cart"></i></a>
                                                </button>
                                            </form>
                                        </li>
                                    </ul>
                                </div>
                                <div class="product__item__text">
                                    <h6><a href="~/home/Details/@product.ID">@product.Name</a></h6>
                                    <h5>@(product.Price - (product.Price * product.Discount / 100)) L.E</h5>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <div style="text-align:center" class="product__pagination">
                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        <a href="@Url.Action("Index", new { page = i })">@i</a>
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Product Section End -->

MarketWebApp/Views/Shop/Product.cshtml
 @model dynamic
@{
    ViewData["Title"] = "Shop";
}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg=@Url.Content("~/img/breadcrumb.jpg")>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Se7teenW3fia Shop</h2>
                    <div class="breadcrumb__option">
                        <a href="./index.html">Home</a>
                        <span>Shop</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->
<!-- Product Section Begin -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-5">
                <div class="sidebar">
                    <div class="sidebar__item">
                        <h4>Department</h4>
                        <ul>
                            @foreach (var Catagory in ViewBag.Categories)
                            {
                                <li><a href="~/shop/product/@Catagory.ID">@Catagory.Name</a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-7">
                <div class="product__discount">
                    <div class="section-title product__discount__title">
                        <h2>Sale Off</h2>
                    </div>
                    <div class="row">
                        <div class="product__discount__slider owl-carousel">
                            @foreach (var DProduct in Model.Discount)
                            {
                                <div class="col-lg-4">
                                    <div class="product__discount__item">
                                        <div class="product__discount__item__pic set-bg" data-setbg=@Url.Content("~/img/product/" + DProduct.Img)>
                                            <div class="product__discount__percent">-@DProduct.Discount %</div>
                                            <ul class="product__item__pic__hover">
                                                <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                                <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                                <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="product__discount__item__text">
                                            <h5><a href="~/home/Details/@DProduct.ID">@DProduct.Name</a></h5>
                                            <div class="product__item__price">@(DProduct.Price - (DProduct.Price * DProduct.Discount / 100))  L.E<span>@DProduct.Price L.E</span></div>
                                        </div>
                                    </div>
                                </div>
                            };

                        </div>
                    </div>
                </div>
                <div class="filter__item">
                    <div class="row">
                        <div class="col-lg-4 col-md-5">
                        </div>
                        <div class="col-lg-4 col-md-3">
                            <div class="filter__found">
                                <h6><span>@Model.Count</span> Products found</h6>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="row">
                    @foreach (var product in Model.Products)
                    {
                        <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="product__item">
                                <div class="product__item__pic set-bg" data-setbg=@Url.Content("~/img/product/" + product.Img)>
                                    <ul class="product__item__pic__hover">
                                        <li>
                                            <form asp-action="AddProductToWish" asp-controller="WishList" asp-route-id="@product.ID">
                                                <button type="submit" style="border:none; background-color:transparent">
                                                    <a><i class="fa fa-heart"></i></a>
                                                </button>
                                            </form>
                                        </li>
                                        <li>
                                            <form method="post" asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@product.ID">
                                                <button type="submit" style="border:none; background-color:transparent">
                                                    <a><i class="fa fa-shopping-cart"></i></a>
                                                </button>
                                            </form>
                                        </li>
                                    </ul>
                                </div>
                                <div class="product__item__text">
                                    <h6><a href="~/home/Details/@product.ID">@product.Name</a></h6>
                                    <h5>@(product.Price - (product.Price * product.Discount / 100)) L.E </h5>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Product Section End -->